#[derive(Debug, Clone)]
pub enum Action {
    Tick,
    Resize(u16, u16),
    Quit,
    OpenHelp,
    CloseHelp,
    OpenSearch,
    CloseSearch,
    SelectCategory(usize),
    OpenTool(usize),
    CloseTool,
    ToggleFavorite(String),
    StartInstall(String),
    ConfirmInstall(String),
    CancelInstall,
    StartRemove(String),
    ConfirmRemove(String),
    CancelRemove,
    LaunchExecutable(String),
    SyncDatabase,
    StatusMessage(String),
    ErrorMessage(String),
}
